// Sample quiz result data, structured to mirror demo.heyhi.sg's marking view.
// Generic shape so OE / Essay / Speech question types can slot in later
// via the same `aiFeedback` field (see README notes in pdf-generator.js).

const quizResult = {
  studentName: "Samantha Wardhana",
  attempt: "6/6",
  totalMarks: 1.5,
  maxMarks: 33,
  percentage: 5,
  questions: [
    {
      number: "1",
      type: "rewrite",
      prompt:
        "Rewrite the given sentence using the words provided. Your answer must be in one sentence. The meaning of your sentence must be the same as the meaning of the given sentence.",
      passage: "The two pupils quarrelled once Mrs Ong left the classroom.",
      studentAnswer:
        "No sooner had mrs ong left the classroom than the two pupils quarreleld reqrite the given sentence",
      modelAnswer:
        "had Mrs Ong left the classroom than the two pupils quarrelled",
      marksObtained: 1.5,
      maxMarks: 2,
      aiFeedback: {
        style: "Simplified",
        text: "Good use of the inversion structure 'No sooner had...than'. Watch capitalisation of 'Mrs Ong' and check spelling of 'quarrelled'. Remove the extra instruction text ('rewrite the given sentence') that was left in the answer.",
      },
    },
    {
      number: "2A",
      type: "mcq",
      prompt: "Look at the visual text and answer the following questions.",
      question: "Which of the following is the main target group of this leaflet?",
      options: [
        { text: "Children and youth", correct: true },
        { text: "Young working adults", correct: false },
        { text: "Authors and illustrators", correct: false },
        { text: "All members of the public", correct: false },
      ],
      studentAnswer: null,
      marksObtained: null,
      maxMarks: 1,
    },
    {
      number: "2B",
      type: "mcq",
      prompt: "Look at the visual text and answer the following questions.",
      question: "Which statement best describes the main purpose of the Festival of Books?",
      options: [
        { text: "For authors to autograph books", correct: false },
        { text: "For young people to be excited about books", correct: true },
        { text: "For members of the public to purchase books at a good price", correct: false },
        { text: "For book publishers to showcase the new books they have published", correct: false },
      ],
      studentAnswer: null,
      marksObtained: null,
      maxMarks: 1,
    },
    {
      number: "2C",
      type: "mcq",
      prompt: "Look at the visual text and answer the following questions.",
      question: "If someone has a question about the Festival of Books, he should _________.",
      options: [
        { text: "buy a festival pass", correct: false },
        { text: "contact Ms Donna Leng", correct: true },
        { text: "wait for the start of the Festival of Books", correct: false },
        { text: "visit the Chancery Community Field website", correct: false },
      ],
      studentAnswer: null,
      marksObtained: null,
      maxMarks: 1,
    },
    {
      number: "2D",
      type: "mcq",
      prompt: "Look at the visual text and answer the following questions.",
      question:
        "Mary is a budding writer and dreams of publishing her work. She ought to purchase a festival pass for the ____________ Booth.",
      options: [
        { text: "Read Aloud to Me", correct: false },
        { text: "Discover an Author", correct: true },
        { text: "Tickle my Taste buds", correct: false },
        { text: "Create your own Superhero", correct: false },
      ],
      studentAnswer: null,
      marksObtained: null,
      maxMarks: 1,
    },
    {
      number: "2E",
      type: "mcq",
      prompt: "Look at the visual text and answer the following questions.",
      question: "Based on the information given in the brochure which of the following statements is false?",
      options: [
        { text: "Everyone visiting the festival must pre-register prior the event", correct: true },
        { text: "You may visit the Festival of Books on any of the published dates", correct: false },
        { text: "The Bookshop will be open daily throughout the entire Festival of Books", correct: false },
        { text: "The Festival of Books is being organised by the Singapore Book Council", correct: false },
      ],
      studentAnswer: null,
      marksObtained: null,
      maxMarks: 1,
    },
    {
      number: "2F",
      type: "mcq",
      prompt: "Look at the visual text and answer the following questions.",
      question: "Which statement best describes the past attendees of the festival?",
      options: [
        { text: "They participated in the cooking demonstration", correct: false },
        { text: "They were barely satisfied with the program offered", correct: false },
        { text: "They had many different experiences that left lasting memories", correct: true },
        { text: "They were pleased to receive a free book for being an early visitor to the festival.", correct: false },
      ],
      studentAnswer: null,
      marksObtained: null,
      maxMarks: 1,
    },
    {
      number: "2G",
      type: "mcq",
      prompt: "Look at the visual text and answer the following questions.",
      question: "What is the main purpose of the leaflet?",
      options: [
        { text: "to promote awareness of the Festival of Books", correct: true },
        { text: "to aid in distributing tickets to the Festival of Books", correct: false },
        { text: "to advertise the content for all the special booths for the Festival of Books", correct: false },
        { text: "to attract book shops sellers to promote their books at the Festival of Books", correct: false },
      ],
      studentAnswer: null,
      marksObtained: null,
      maxMarks: 1,
    },
    {
      number: "2H",
      type: "mcq",
      prompt: "Look at the visual text and answer the following questions.",
      question: "Why are the titles of the specialist booths printed in bold?",
      options: [
        { text: "to beautify the leaflet", correct: false },
        { text: "to advertise the festival", correct: false },
        { text: "to promote visits to the specialist booths", correct: true },
        { text: "to raise awareness of the special guests at the festival", correct: false },
      ],
      studentAnswer: null,
      marksObtained: null,
      maxMarks: 1,
    },
    {
      number: "3",
      type: "rewrite",
      prompt:
        "Rewrite the given sentences using the words provided. Your answer must be in one sentence. The meaning of your sentence must be the same as the meaning of the given sentences.",
      passage: "John shouted at Mary. He did not consider her feelings.",
      studentAnswer: "Without any",
      modelAnswer: "consideration for her feelings, John shouted at Mary",
      marksObtained: 0,
      maxMarks: 2,
      aiFeedback: null,
    },
    {
      number: "4",
      type: "mcq",
      prompt: null,
      question: '"If the salesperson calls again, I _____ him a piece of my mind!" Mrs Tang exclaimed.',
      options: [
        { text: "will give", correct: true },
        { text: "would give", correct: false },
        { text: "will have given", correct: false },
        { text: "would have given", correct: false },
      ],
      studentAnswer: null,
      marksObtained: null,
      maxMarks: 1,
    },
  ],
};
